Output fretty-mercury.mp4

# Set up a 1200x600 terminal with 46px font.
#
Set WindowBar Colorful
Set FontSize 26
Set Width 2560
Set Height 800
Set Margin 60
Set MarginFill "#6B50FF"
Set Shell zsh
Set BorderRadius 10

# Type a command in the terminal.
Type "./lua main.lua"

# Pause for dramatic effect...
Sleep 250ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 2s
